@BASE_URL=http://localhost:3000/api

//Kullanıcı kayıt olma
###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "isim":"",
    "soyisim":"",
    "email":"",
    "sifre":""
}

//Giriş yapma
###
POST {{BASE_URL}}/users/giris
Content-Type: application/json

{
    "email":"",
    "sifre":""
}

//Kendini güncelleme
###
PATCH {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: Bearer --token gelecek--

{
    "soyisim":""
}

//Admin tüm kullanıcıları listeliyor
###
GET {{BASE_URL}}/users
Authorization: Bearer --token gelecek--

//Oturum açan kullanıcı bilgileri
###
GET {{BASE_URL}}/users/me
Authorization: Bearer --token gelecek--


//Kişi kendini siliyor
###
DELETE {{BASE_URL}}/users/me
Authorization: Bearer --token gelecek--


###
GET {{BASE_URL}}/kategoriler


###
POST {{BASE_URL}}/ahsaplar
Content-Type: application/json

{
    "sha": "",
    "email": "",
    "tur": "",
    "miktar": 2,
    "verilenKarbon": 400
}

###
PATCH {{BASE_URL}}/users/sha gelecek
Content-Type: application/json
Authorization: Bearer --token gelecek--

{
    "karbonMiktari":1600
}

###
DELETE {{BASE_URL}}/camlar/id gelecek
Authorization: Bearer --token gelecek--

###
PATCH {{BASE_URL}}/users/sha gelecek
Content-Type: application/json
Authorization: Bearer --token gelecek--

{
    "gonderilenCoin":150
}
    
###
GET {{BASE_URL}}/ahsaplar


###
GET {{BASE_URL}}/ahsaplar/e-mail gelecek