@BASE_URL=http://localhost:3000/api

//Kullanıcı kayıt olma
###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "isim":"asdf",
    "soyisim":"asdg",
    "email":"sadgasdg@gmail.com",
    "sifre":"123456"
}

//Giriş yapma
###
POST {{BASE_URL}}/users/giris
Content-Type: application/json

{
    "email":"hasansahin@gmail.com",
    "sifre":"hasan1234"
}

//Kendini güncelleme
###
PATCH {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: Bearer --token gelecek--

{
    "soyisim":""
}

//Admin tüm kullanıcıları listeliyor
###
GET {{BASE_URL}}/users
Authorization: Bearer --token gelecek--

//Oturum açan kullanıcı bilgileri
###
GET {{BASE_URL}}/users/me
Authorization: Bearer --token gelecek--


//Kişi kendini siliyor
###
DELETE {{BASE_URL}}/users/me
Authorization: Bearer --token gelecek--


###
GET {{BASE_URL}}/kategoriler

//GERİ DÖNÜŞÜM YAPMA
###
POST {{BASE_URL}}/ahsaplar
Content-Type: application/json

{
    "sha": "fdbccc246491d3c2ca3d10a13f8cf1fc80432c0dfb83f6017d67849b8913e5ce",
    "userName":"ahmetcanerol",
    "email": "ahmetcanerol@gmail.com",
    "tur": "Maun",
    "miktar": 2
}

//COIN TRANSFERİ
###
PATCH {{BASE_URL}}/users/transfer/sha gelecek
Content-Type: application/json
Authorization: Bearer --token gelecek--

{
    "gonderilenCoin":2
}

//ADMİN GERİ DÖNÜŞÜM ONAYLAMA
###
PATCH {{BASE_URL}}/users/ahmetcanerol
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZTU0NDU3Y2M2OGZmYTZmYzU2MzgiLCJpYXQiOjE2NzE5MDY2ODcsImV4cCI6MTY3MTkxMDI4N30.U211E0VsSG0vXitPXBzN3CKvK_6F2FcAQSgaXrnII2w

{
    "_id":"63a71289ed40fd4e96649e34",
    "tur":"Ahsap",
    "karbonMiktari":600
}

//ADMİN GERİ DÖNÜŞÜM REDDETME
###
DELETE {{BASE_URL}}/camlar/id gelecek
Authorization: Bearer --token gelecek--

###
GET {{BASE_URL}}/kategoriler/elektronikTurleri

###
GET {{BASE_URL}}/ahsaplar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZTU0NDU3Y2M2OGZmYTZmYzU2MzgiLCJpYXQiOjE2NzE4ODU2OTgsImV4cCI6MTY3MTg4OTI5OH0.rmB4dIr77cuulCFisi1sYJrLDnmWks68Fjhfc48qzJU


